[profile.default]
src = 'src'
out = 'artifacts'
libs = [
    'lib',
    'node_modules',
]
remappings = [
    '@aave/=node_modules/@aave/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@solidstate/=node_modules/@solidstate/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config