[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
  "solidity-stringutils/=lib/solidity-stringutils/src/",
  "solidstate-solidity/=lib/solidstate-solidity/contracts/",
  "ERC721A-Upgradeable/=lib/ERC721A-Upgradeable/contracts"
]
fs_permissions = [{ access = "read-write", path = "./"}]
ffi = true
deny_warnings = false
via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
goerli = "${GOERLI_INFURA_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config